filter:
    excluded_paths:
      - Tests/*
      - vendor/*

tools:
    sensiolabs_security_checker: true

build:
    environment:
        php:
            ini:
                memory_limit: "-1"
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
