build: false
shallow_clone: true
platform: x86
clone_folder: C:\projects\twig-constants

environment:
    matrix:
        - PHP_DOWNLOAD_FILE: php-5.4.44-nts-Win32-VC9-x86.zip
        - PHP_DOWNLOAD_FILE: php-5.5.35-nts-Win32-VC11-x86.zip
        - PHP_DOWNLOAD_FILE: php-5.6.21-nts-Win32-VC11-x86.zip
        - PHP_DOWNLOAD_FILE: php-7.0.6-nts-Win32-VC14-x86.zip

cache:
    - c:\php -> appveyor.yml
    - '%LOCALAPPDATA%\Composer'

init:
    - SET PATH=C:\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET PHP=1

install:
    - IF EXIST c:\php (SET PHP=0) ELSE (mkdir c:\php)
    - cd c:\php
    - IF %PHP%==1 appveyor DownloadFile http://windows.php.net/downloads/releases/archives/%PHP_DOWNLOAD_FILE%
    - IF %PHP%==1 7z x %PHP_DOWNLOAD_FILE% -y > 7z.log
    - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
    - appveyor DownloadFile https://getcomposer.org/composer.phar
    - copy php.ini-production php.ini /Y
    - echo date.timezone="Europe/Paris" >> php.ini
    - echo extension_dir=ext >> php.ini
    - echo extension=php_openssl.dll >> php.ini
    - echo extension=php_curl.dll >> php.ini
    - echo extension=php_mbstring.dll >> php.ini
    - echo extension=php_fileinfo.dll >> php.ini
    - appveyor DownloadFile https://getcomposer.org/composer.phar
    - cd c:\projects\twig-constants
    - php c:\php\composer.phar install

test_script:
    - cd C:\projects\twig-constants
    - vendor\bin\phpunit.bat
